language: java

jdk:
  - openjdk8
  - openjdk11

before_install:
  - sudo apt update
  - sudo apt install openjfx

install: skip
script: mvn install -Dgpg.skip=true --batch-mode --show-version --update-snapshots

cache:
  directories:
    - $HOME/.m2