language: java

cache:
  directories:
    - $HOME/.m2
    
jdk:
  - openjdk8
  - openjdk11

before_install:
  - sudo apt update
  - sudo apt install openjfx
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
  

before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')


script: mvn install --batch-mode --show-version --update-snapshots

