language: java
    
jdk:
  - openjdk8
#   - openjdk11

cache:
  directories:
    - $HOME/.m2
    
before_install:
  - sudo apt update
  - sudo apt install openjfx
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export PROJECT_VERSION=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')

install:
  - mvn package --settings .maven.xml --batch-mode --show-version --update-snapshots -Dmaven.javadoc.skip=true

before_script:
  - if [ $TRAVIS_BRANCH == "develop" ] && [[ $PROJECT_VERSION != *-SNAPSHOT ]]; then echo 'Snapshot version does not end with -SNAPSHOT' && exit 1; fi
  - if [ $TRAVIS_BRANCH == "master" ] && [[ $PROJECT_VERSION == *-SNAPSHOT ]]; then echo 'Release version ends with -SNAPSHOT' && exit 1; fi

script:
  - if [ $TRAVIS_BRANCH == "develop" ] && [ $TRAVIS_PULL_REQUEST == "false" ]; then mvn deploy --settings .maven.xml --batch-mode --show-version -Psnapshot -DskipTests=true; fi
  - if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST == "false" ]; then mvn deploy --settings .maven.xml --batch-mode --show-version -Prelease -DskipTests=true; fi

# before_deploy:
#   - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')


# https://docs.travis-ci.com/user/environment-variables/
